// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRestAPI.Model;

#nullable disable

namespace StudentRestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRestAPI.Model.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("cf5a1241-276e-4b17-9d9a-0a06026724de"),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "patrick.gonzaga@yahoo.com",
                            FirstName = "Patrick James",
                            Gender = 0,
                            LastName = "Gonzaga",
                            PhotoPath = "Images/PatrickGonzaga.png"
                        },
                        new
                        {
                            StudentId = new Guid("738b7c16-e15e-4a54-86aa-52139dcaa74f"),
                            DateOfBirth = new DateTime(1982, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "robert.gonzaga@yahoo.com",
                            FirstName = "Robert James",
                            Gender = 0,
                            LastName = "Gonzaga",
                            PhotoPath = "Images/RobertGonzaga.png"
                        },
                        new
                        {
                            StudentId = new Guid("b1f108f7-f437-4c2a-a36f-51b0eddd5b29"),
                            DateOfBirth = new DateTime(2005, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "michael.gonzaga@yahoo.com",
                            FirstName = "Michael James",
                            Gender = 0,
                            LastName = "Gonzaga",
                            PhotoPath = "Images/MichaelGonzaga.png"
                        },
                        new
                        {
                            StudentId = new Guid("b107100c-74ca-4b67-8444-f268ae74b915"),
                            DateOfBirth = new DateTime(2010, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "christine.gonzaga@yahoo.com",
                            FirstName = "Christine Joannn",
                            Gender = 1,
                            LastName = "Gonzaga",
                            PhotoPath = "Images/ChristineGonzaga.png"
                        },
                        new
                        {
                            StudentId = new Guid("8321334d-4d63-40f4-ad35-042ef9dd63ce"),
                            DateOfBirth = new DateTime(2015, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "barbra.gonzaga@yahoo.com",
                            FirstName = "Barbra Joann",
                            Gender = 1,
                            LastName = "Gonzaga",
                            PhotoPath = "Images/BarbraGonzaga.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
